name: dart_server
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: firatcetiner <firat.cetiner@trioworx.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  args: ^1.5.0
  shelf: ^0.7.5
  postgres: 2.1.0
  dart_mssql: 1.0.1
  grpc: 2.1.3

dev_dependencies:
  pedantic: ^1.8.0
